### ISSUE TITLE
OOS refuses to open zip file

### ISSUE THREAD

**Issue by rlucassen2** [c4ffein/OOS-firmware-updater#2]
- Oneplus 5, LineageOS-16 cheeseburger for A5000
- firmware 9.0.5, updated a few weeks ago using OOS-firmware-updater
- Repository: F-droid, version 0.3.0
- Downloaded [Oxygen stock rom](https://www.oneplus.com/support/softwareupgrade/details?code=5)
- md5sum ok

Tried to update to 9.0.6, opened OOS, the OOS file manager shows the file but refuses to open it. OOS has permissions to read the Download folder.

Any thoughts?

Richard.

**Comment by c4ffein** [comment]
I don't have a Oneplus 5 to test on, but on my main phone, I had no problems using the latest Lineage OS, which should be nearly identical to yours, just minutes ago. The file manager is supposed to be the system's one, I didn't use any custom solution.

I am aware of a little problem on the Android Emulator, where I had to long-press the zip file and then select the "open" option, otherwise I would just have opened the content of it in the file manager. Still, it shouldn't be a problem, as this is a known behavior of the emulator, was supposed to work fine on all real phones, and I have never actually seen this on any of my devices. Maybe you can try to long-pressing the zip file?

Also, can you confirm the file manager you are seeing when trying to select a file is the default one from Lineage OS?

**Comment by c4ffein** [comment]
Also, can you check that your rom file name is ending with .zip? Android uses that to check that this file is really a zip file, contrarily to a lot of Unix systems which would check for the zip magic number at the beginning of the file.

**Comment by rlucassen2** [comment]
I was sure that it was a zip file, but the filename was too long to check it and so I renamed the file "OnePlus5Oxygen_23_OTA_049_all_1905271752_a42586e0ab6e45b0.zip" to "OnePlus5Oxygen.zip" and now it's not greyed out anymore. Don't ask me why, but this smells like a bug in the file manager.

Maybe you can test if you encounter the same issue with this long filename.

Richard

**Comment by rlucassen2** [comment]
FYI: I extracted, checked and cooked the firmware succesfully. Then I ran "adb sideload firmwareupdater.zip" without any problem.

R.

**Comment by c4ffein** [comment]
Well, as I use the default file manager and not a third party library for both maintainability and consistency reasons, there is not so much that I can do if some versions can't select a file if the name is too long. I also tested the file you linked with the default filename, using the latest version of Lineage on one of my devices, and it worked at first try.

Also, maybe the file was greyed out because download had not finished?
If you are curious, the code is right there : https://github.com/c4ffein/OOS-firmware-updater/blob/a421aaa74e1c4155e86fc89711c5d7d26d540a76/app/src/main/java/fr/witchdoctors/c4ffein/oosfirmwareextractor/MainActivity.java#L53-L58

As you can see it uses a functionality of Android itself, if you can reproduce this bug again, maybe you can reach the Lineage team.

Anyway, thank you for your feedback, and glad you made it work in the end!

**Comment by rlucassen2** [comment]
Well, for the moment it works, I got the latest LineageOS running and next time when I will have to get through the firmware update process again, I'll try it. And if someone else stumbles upon this issue, he or she will find this thread ;-)

Richard.

Kernighan's (or Ritchie's) description of a bug: "a computer does what you ask, not what you want"

**Comment by rlucassen2** [comment]
I just updated to 9.0.8 using the large filename. Maybe a bug in the default filemanager.

R.
