### ISSUE TITLE
Reflash ROM after using OOS-firmware-updater?

### ISSUE THREAD

**Issue by stef204** [c4ffein/OOS-firmware-updater#4]
A little out of scope perhaps but let me ask:

I am about to flash the `firmwareupdater.zip` generated on `dumpling` (OP5T) to upgrade the firmware.  I am already running a custom ROM.  Do you know if one has to re-flash the (same) custom ROM after having flashed the updated firmware?

Or does one just reboot and pick up where one left off?

**Comment by c4ffein** [comment]
Updated the README, you can reopen if still unclear
You can also create a new issue to tell me if it worked or not with any OnePlus > 5t

**Comment by stef204** [comment]
Thanks.  This is what I've noticed: the files inside the `firmware-update` directory inside the `firmwareupdater.zip` generated by this app and the same files inside the same directory in custom ROM's own install zip are **identical**, using `diff` or `vbindiff`.  This would seem to mean that the previous install of custom ROM already updated the firmware. This include `static_nvbk.bin`.

The only difference I see in files extracted from `OOS` by this app is `boot.img` which differs from the custom ROM's own `boot.img`.  This is likely to cause problems and might need to be overwritten with the custom ROM's own `boot.img`  to avoid problems, if I did flash the `firmwareupdater.zip`.

In my particular situation, I am not seeing where I would benefit from overwriting my firmware from custom ROM with what appears to be identical firmware from `OOS`.

PS This thread is probably out of scope or somewhat off-topic I suppose.

**Comment by c4ffein** [comment]
I was surprised by what you just said so I checked: yes, `boot.img` ends-up included in the zip file, I don't remember why, maybe TWRP refuses to flash a zip not including a `boot.img`, maybe I just forgot to put it out of the list of files that we want to keep in the zip.

But it does not matter as it is not flashed by the custom generated `updater-script` (that you can check from the app), so you would have been safe if you flashed `firmwareupdater.zip`.
Personally I use Lineage on some devices, and Lineage doesn't include firmware updates while sometimes requiring the latest firmware (for FLOSS reasons I guess, but since we need that closed-source software running on the phone anyway...)

Obviously the developers of your ROM save your time and include the latest firmware, so you don't really need my app

**Comment by stef204** [comment]
Yes, I checked your `updater-script` against the one included in the custom ROM and it looks just fine. I see how `boot.img` is excluded and how it would only upgrade the firmware files; and in the right directories, etc.  Nifty!

About LineageOS. The firmware files ARE included in the install ZIP.
Look [here](https://paste.xinu.at/oKL/) for LineageOS 19.1 (Android 12.)
The first directory `firmware-update` is from your extracted zip file and the second directory is from the extracted LOS zip install file.
You can see the diff I did and the files are identical.  That is why I do not see a need to again "update" the firmware.  Unless the `META-INF/com/google/android/updater-script` is not run during install or update of LOS (but that's just rather unlikely; it would mean LOS uses a different means to update.)

**Comment by c4ffein** [comment]
Either:
- LineageOS includes those files but does not flash them through the `updater-script`, very unlikely
- LineageOS doesn't include those files in the OTA I received on my phone but those were present through web, also unlikely
- LineageOS didn't include those when I wrote that tool but now does. I would guess that is the case, as official end of support for my device was reached in something like 2019, maybe Lineage started shipping those files since then, but I couldn't tell the difference as I was already at the latest firmware/radio version. And I wasn't the only one encountering that problem, see [that Reddit post](https://www.reddit.com/r/LineageOS/comments/bh5mta/should_i_flash_the_newest_vendor_firmware_before/) for exemple

Anyway just updated the `README` one last time, just in case

**Comment by stef204** [comment]
OP5T (`dumpling`) is still fully supported by LOS, in case you still have your device. See [here](https://download.lineageos.org/dumpling).

Anyway, thanks for the app.  I would not hesitate to use it if needed, now that I have looked at it in more detail.
And FWIW, the UX is not "really bad":  it just works!<sup>TM</sup> ;)

**Comment by c4ffein** [comment]
By `official end of support` I meant the OxygenOS one. No OxygenOS updates -> no ROM to get official firmware updates from... I know I still get Lineage OTA on that device, but never had to flash firmware to make those work since the end of the OxygenOS support.

No, the UX is terrible, if I had to explain what it does, it is... It's counter-intuitive, the default Android buttons don't make enough of a difference when disabled or not, the process could be split between multiple screens... Anyway it's a FLOSS app, and FLOSS users learnt to have low expectations, and it's not like I will still get many of them since it seems Lineage finally includes those files.

Thanks for your feedback in any case!
